In [2]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import json


In [3]:
train = pd.read_json("C:\\Users\\Devika K T\\Desktop\\output .json")

In [4]:
print(train.shape)

(692, 10)


In [5]:
train.keys()

Index(['Id', 'UserID', 'No Of Abuse Report', 'No Of Rejected Friend Requests',
       'No Of Freind Requests Thar Are Not Accepted', 'No Of Friends',
       'No Of Followers', 'No Of Likes To Unknown Account',
       'No Of Comments Per Day', 'Fake Or Not Category'],
      dtype='object')

In [6]:
train = train.astype(int)

In [7]:
x =np.array(train.drop(['Fake Or Not Category'],axis = 1))

In [8]:
x

array([[  1,   1,  37, ..., 838,  26,  53],
       [  2,   2,  63, ..., 349,  37,  58],
       [  3,   3,  10, ..., 271,  73,  11],
       ...,
       [690, 690,  87, ..., 282,  85,  40],
       [691, 691,  24, ..., 554,  56,  97],
       [692, 692,  68, ..., 299,  72,  91]])

In [9]:
y = np.array(train['Fake Or Not Category'])

In [10]:
y

array([1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = .25,random_state = 2)

In [13]:
rf = RandomForestClassifier()

In [14]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [15]:
y_test_predict = rf.predict(x_test)

In [16]:
Accuracy_test = metrics.accuracy_score(y_test_predict,y_test)

In [17]:
Accuracy_test 

1.0

In [18]:
x[0].reshape(1,-1).shape

(1, 9)

In [19]:
rf.predict(x[0].reshape(1,-1))

array([1])

In [20]:
import pickle 

In [21]:
pickle.dump(rf,open('rfmodel.pkl','wb'))

In [22]:
pickled_model = pickle.load(open('rfmodel.pkl','rb'))

In [23]:
pickled_model.predict(x[0].reshape(1,-1))

array([1])